#! /usr/bin/env node

/************************************************************************
 *
 *  fspage2mml
 *
 *  Reads an HTML5 file from stdin that contains math
 *  and writes a new HTML5 document to stdout that
 *  contains MathML versions of the math instead.
 *
 * ----------------------------------------------------------------------
 *
 *  Copyright (c) 2014 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

var typeset = require("../lib/mj-page.js").typeset;
var fs = require('fs');
var jsdom = require('jsdom').jsdom;

//
//  Produce a Usage message, if needed
//
if (process.argv.length !== 4) {
  console.error("Usage: fspage2mml input.html  output.html");
  process.exit(1);
}

var inputFile = process.argv[2];
var outputFile = process.argv[3];

//
//  Process an HTML file:
//
function processHTML(html,callback) {
  var document = jsdom(html);
  typeset({html:document.body.innerHTML, renderer:"NativeMML"}, function (result) {
    document.body.innerHTML = result.html;
    var HTML = "<!DOCTYPE html>\n"+document.outerHTML.replace(/^(\n|\s)*/,"");
    callback(HTML);
  });
}

//
//  Read the input file, process the HTML, write output file.
//

var html = fs.readFileSync(inputFile, "utf8");

processHTML(html, function (html) {
    fs.writeFile(outputFile, html, function (err) {
        if (err) throw err;
        console.log("It\'s saved!");
    });
});